name: DNN-based_source_separation_tutorials-gpu

channels:
  - pytorch
  - defaults
  - conda-forge

dependencies:
  - python>=3.6,<=3.8
  - numpy>=1.19
  - matplotlib>=3.1.3
  - pytorch>=1.8.0
  - torchaudio>=0.8.0
  - cudatoolkit>=10
  - mir_eval==0.6
  - pyaudio>=0.2.11